environment        = "dev"
project_name       = "oyd-project"
region             = "us-east-1"
bucket_name_prefix = "oyd"
db_name            = "parking_db"
db_username        = "parking_user"
db_engine_version  = "16.14"