export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    changePassword: '/auth/change-password',
  },
  driver: {
    vehicles: '/me/vehicles',
    vehicle: (id: number) => `/me/vehicles/${id}`,
    reservations: '/me/reservations',
  },
  availability: '/availability',
  reservations: {
    create: '/reservar',
    get: (id: number) => `/reservations/${id}`,
    confirm: (id: number) => `/reservations/${id}/confirm`,
    release: (id: number) => `/reservations/${id}/release`,
    cancel: (id: number) => `/reservations/${id}/cancel`,
    receipt: (id: number) => `/reservations/${id}/receipt`,
  },
  tariffs: {
    public: '/tariffs',
    admin: '/admin/tariffs',
  },
  admin: {
    users: '/admin/users',
    user: (id: number) => `/admin/users/${id}`,
    userActivate: (id: number) => `/admin/users/${id}/activate`,
    userDeactivate: (id: number) => `/admin/users/${id}/deactivate`,
    vehicles: '/admin/vehicles',
    vehicleApprove: (id: number) => `/admin/vehicles/${id}/approve`,
    spaces: '/admin/spaces',
    space: (id: number) => `/admin/spaces/${id}`,
    spaceActivate: (id: number) => `/admin/spaces/${id}/activate`,
    spaceDeactivate: (id: number) => `/admin/spaces/${id}/deactivate`,
    spaceBlackouts: (spaceId: number) => `/admin/spaces/${spaceId}/blackouts`,
    blackout: (id: number) => `/admin/blackouts/${id}`,
    dashboard: '/admin/dashboard/occupancy',
    reservations: '/admin/reservations',
    reservationsExport: '/admin/reservations/export',
    settings: '/admin/settings',
    setting: (key: string) => `/admin/settings/${key}`,
  },
  health: '/health',
  ready: '/ready',
} as const;
