name: Terraform CI - OyD 

on:
  pull_request:
    branches: # Workflow that runs on every pull request targeting the main branch
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true #Node.js 20 actions are deprecated. This forces all actions to use Node.js 24, which is the latest supported version.
  env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "~> 1.8"


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt --check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=envs/dev/dev.tfvars -no-color 2>&1 | tee plan.txt

      - name: Post plan as PR comment
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('infra/plan.txt', 'utf8');
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `<details><summary>Terraform Plan</summary>\n\n\`\`\`\n${plan}\n\`\`\`\n</details>`
            });